name:                LibrarianXlsx
version:             0.1.0.0
github:              "githubuser/LibrarianXlsx"
license:             MIT
author:              "Nicolas Soncini"
maintainer:          "soncininicolas@gmail.com"
copyright:           "2017 Nicolas Soncini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/LibrarianXlsx#readme>

dependencies:
- base >= 4.7 && < 5
- text
- lens
- bytestring
- time
- xlsx
- mtl
- transformers
- readline
- parsec
- ansi-terminal
- containers
- parsec3-numbers

library:
  source-dirs: src

executables:
  LibrarianXlsx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LibrarianXlsx

tests:
  LibrarianXlsx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LibrarianXlsx
